baseURL: https://writory.org/
copyright: "Original content released under the [MIT License](https://github.com/MichaelSchmidle/writory-hugo/blob/master/LICENSE)"
title: Writory
theme: writory-hugo-theme

params:
  authors: ["[Michael Schmidle](https://blog.ypertex.com/authors/michael-schmidle/)"]
  description: Documentation and showcase of the [Writory theme](https://github.com/MichaelSchmidle/writory-hugo-theme) for [Hugo](https://gohugo.io/)
  logo: writory-logo-h.svg
  logogram: writory-logogram.svg
  thirdPartyReferences: [
      "Mirage illustrations licensed by [Icons8 LLC.](https://icons8.com/)",
      "Made with [Hugo](https://gohugo.io/) and [Bootstrap](https://getbootstrap.com/)"
    ]

taxonomies:
  author: authors
  series: series
